#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
#if (( $+commands[gvim] )); then
#  export VISUAL='gvim'
#fi
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# XXX: Might not need these when using the python module
# in .zpreztorc.

# virtualenvwrapper settings
# export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python
# export VIRTUALENVWRAPPER_PYTHON=~/.pyenv/shims/python
# export WORKON_HOME=$HOME/.virtualenvs
# export PROJECT_HOME=$HOME/projects/python
# export VIRTUALENVWRAPPER_VIRTUALENV_ARGS='--no-site-packages'

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/bin
  /usr/local/sbin
  $HOME/.local/bin
  $HOME/.cabal/bin
  $HOME/apps/Zotero_linux-x86_64
  $path
)
path=($HOME/apps/anaconda3/bin $path)
path=($path $(npm bin 2> /dev/null))

# Remove non-valid paths
for x in "${path[@]}"; do
  if [ ! -d "$x" ]; then
    path=("${(@)path:#$x}")
  fi
done

if ! type pyenv | grep -q function; then # only once!
  if [ -n "$commands[pyenv]" ] ; then
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
    pyenv virtualenvwrapper_lazy
  fi
fi

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#
#
# Set TMPDIR if the variable is not set/empty or the directory doesn't exist
if [[ -z "${TMPDIR}" ]]; then
  export TMPDIR="/tmp/zsh-${UID}"
fi

if [[ ! -d "${TMPDIR}" ]]; then
  mkdir -m 700 "${TMPDIR}"
fi
