#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
#if (( $+commands[gvim] )); then
#  export VISUAL='gvim'
#fi
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# XXX: Might not need these when using the python module
# in .zpreztorc.
export PYENV_ROOT=$HOME/.pyenv
export PYENV_VIRTUALENVWRAPPER_PREFER_PYVENV="true"
export PYENV_VIRTUALENV_DISABLE_PROMPT=1

# virtualenvwrapper settings
# export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python
export VIRTUALENVWRAPPER_PYTHON=~/.pyenv/shims/python
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/projects/python
#export VIRTUALENVWRAPPER_VIRTUALENV_ARGS='--no-site-packages'

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/bin
  /usr/local/sbin
  $HOME/.local/bin
  $HOME/.cabal/bin
  $HOME/apps/Zotero_linux-x86_64
  $path
  /usr/local/bin
  /usr/local/sbin
)

# pyenv settings
# eval "$(pyenv init -)"
# if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi
# pyenv virtualenvwrapper
# source /usr/local/bin/virtualenvwrapper.sh
# source ~/.pyenv/shims/virtualenvwrapper.sh

if ! type pyenv | grep -q function; then # only once!
  if [ -n "$commands[pyenv]" ] ; then
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
    pyenv virtualenvwrapper_lazy
  fi
fi

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi
