#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
bindkey -M viins '^r' history-incremental-search-backward
bindkey -M vicmd '^r' history-incremental-search-backward

export PATH=~/.cabal/bin:/opt/cabal/head/bin:/opt/ghc/7.8.3/bin:/opt/happy/1.19.4/bin:/opt/alex/3.1.3/bin:$PATH

# maybe a fix for xmonad+java issues
export _JAVA_AWT_WM_NONREPARENTING=1

export GOPATH=$HOME/gopath
export PATH=$GOPATH:$GOPATH/bin:$PATH


#. /home/bwillar0/projects/code/torch/install/bin/torch-activate

PATH="/home/bwillar0/perl5/bin${PATH+:}${PATH}"; export PATH;
PERL5LIB="/home/bwillar0/perl5/lib/perl5${PERL5LIB+:}${PERL5LIB}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/home/bwillar0/perl5${PERL_LOCAL_LIB_ROOT+:}${PERL_LOCAL_LIB_ROOT}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"/home/bwillar0/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/home/bwillar0/perl5"; export PERL_MM_OPT;

# needed for vim-r-plugin's vimcom
#alias vim='vim --servername=VIM'
